### ISSUE TITLE
Doesn't work for users like Gill Bates

### ISSUE THREAD

**Issue by bustapaladin** [FinlayDaG33k/MaidBot#1] opened 2016-07-17 22:36 UTC
so if the user has a spacing in the uname field it won't work. 

Easy solution is to change it in contrust to gill_bates but is the other solution that much more work?

**Comment by FinlayDaG33k** [comment] 2016-07-18 08:20
as far as I know, spaces are not allowed in BaB names.  
I've looked up `Gill Bates` on BaB itself, but there is no match. however, `Gill_Bates` does have a match.

**Comment by bustapaladin** [comment] 2016-07-18 08:26
Alright, that is true yes. I changed it on cointrust but no luck.

**Comment by FinlayDaG33k** [comment] 2016-07-18 08:41
Well, this is not a issue with MaidBot.  
you could try using the `str_replace()` function on cointrust to replace spaces in the username (the username that is used as title that is) with underscores.  
This would look like this:  
`str_replace(" ", "_", $user_name);`

**Comment by bustapaladin** [comment] 2016-07-18 09:13
I guess we established now that because hacker was not in lookup this can be classified as a reported bug.

**Comment by FinlayDaG33k** [comment] 2016-07-18 09:14
Yes, it's fixed now and I've already pushed the new version to the Github.
If the issue is solved, please hit the "close" button.

**Closed as completed** 2016-07-18 09:16 UTC
Labels: bug
